const userActionTypes = {
    SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    SIGN_IN_WITH_EMAIL_START: 'SIGN_IN_WITH_EMAIL_START',
};

export default userActionTypes;